export { default as Attractions } from './Attractions'
export { default as Reviews } from './Reviews'
export { default as Slider } from './Slider'
export { default as Venice } from './Venice'
export { default as Warsaw } from './Warsaw'
export { default as Home } from './Home'