export { default as Attractions } from './Attractions/Attractions'
export { default as Reviews } from './Reviews/Reviews'
export { default as Slider } from './Slider/Slider'
export { default as Home } from './Home/Home'
export { default as AllAttractions } from './allAttractions/AllAttractions'
export { default as OneAttraction } from './OneAttraction/OneAttraction'