export { default as Loader } from './Loader/Loader'
export { default as AllCard } from './AllCard/AllCard'
export { default as Card } from './card/Card'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Reviews } from './Reviews/Reviews'